name: rok
channels:
  - conda-forge
dependencies:
  - reaktoro

environment:
  PYTHONPATH:
    - {{ root }}:{{ root }}/firedrake/lib64/python3.7/site-packages:{{ root }}/firedrake/src

  PATH:
    - {{ PATH }}:{{ root }}/firedrake/bin